## Przygotowanie do pracy - import pakietu, sprawdzenie wersji

In [2]:
import numpy as np
np.__version__

'1.20.1'

### Pamiętaj, żeby przy wykonywaniu tych zadań posługiwać się dokumentacją biblioteki numpy!
https://numpy.org/doc/

U góry widoczna jest wersja Twojej biblioteki. Wybierz właściwa dokumentację :)

Zad.1. Stworz wektor (ndarray) o wielkosci 10 elementow. 

In [3]:
Z = np.zeros(10) #moze tez byc jakikolwiek inny, nie ma tu wyspecyfikowanych wartosci

Zad.2. Stworz wektor (ndarray) o wartościach z zakresu od 10 do 109

In [6]:
Z = np.arange(10,110)

In [7]:
Z

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
       101, 102, 103, 104, 105, 106, 107, 108, 109])

Zad.3. Znajdz w dokumentacji numpy funkcję, która odwróci ten wektor. Ostatni jego element ma się stać pierwszym.

In [76]:
#sposob 1 - znany

In [8]:
Z = Z[::-1]

In [9]:
Z

array([109, 108, 107, 106, 105, 104, 103, 102, 101, 100,  99,  98,  97,
        96,  95,  94,  93,  92,  91,  90,  89,  88,  87,  86,  85,  84,
        83,  82,  81,  80,  79,  78,  77,  76,  75,  74,  73,  72,  71,
        70,  69,  68,  67,  66,  65,  64,  63,  62,  61,  60,  59,  58,
        57,  56,  55,  54,  53,  52,  51,  50,  49,  48,  47,  46,  45,
        44,  43,  42,  41,  40,  39,  38,  37,  36,  35,  34,  33,  32,
        31,  30,  29,  28,  27,  26,  25,  24,  23,  22,  21,  20,  19,
        18,  17,  16,  15,  14,  13,  12,  11,  10])

In [77]:
#sposob 2 - nowa funkcja

In [21]:
Z = np.arange(10,110)
np.flip(Z)

array([109, 108, 107, 106, 105, 104, 103, 102, 101, 100,  99,  98,  97,
        96,  95,  94,  93,  92,  91,  90,  89,  88,  87,  86,  85,  84,
        83,  82,  81,  80,  79,  78,  77,  76,  75,  74,  73,  72,  71,
        70,  69,  68,  67,  66,  65,  64,  63,  62,  61,  60,  59,  58,
        57,  56,  55,  54,  53,  52,  51,  50,  49,  48,  47,  46,  45,
        44,  43,  42,  41,  40,  39,  38,  37,  36,  35,  34,  33,  32,
        31,  30,  29,  28,  27,  26,  25,  24,  23,  22,  21,  20,  19,
        18,  17,  16,  15,  14,  13,  12,  11,  10])

Zad.4. Stworz macierz 3x3 o wartościach od 0 do 8.

In [22]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Zad.5. Stworz macierz 10x10 z randomowymi wartościami (jak na początku notebooka z zajęć).

Podaj jej max i min. 

In [30]:
N = np.random.randint(1,10000,(10,10))

In [31]:
N

array([[3296, 9300, 5022, 4382, 7226, 5146, 9746, 4402, 3205, 3420],
       [4459, 9277, 8132, 3009, 3356, 3195, 4194, 7176, 2020, 8782],
       [9822, 3671, 5957,  101, 1866, 4783, 6356, 2125, 6267, 7086],
       [4432, 6797, 3744, 6524, 9478, 1202, 5567, 1587, 7765, 9896],
       [5966, 1263, 5003, 5095, 6635, 8882, 9096, 9525, 4457,   73],
       [5918, 6747, 7849, 5099, 2358, 5638, 4188, 1766, 4584, 4969],
       [2589, 4143, 4994, 9259, 3542,   90, 6371, 5767,  103, 5588],
       [4546, 7021, 4837,  204, 7458, 3059, 6762, 6321, 6568, 4935],
       [9029, 8061, 3660, 4259, 7758, 9911,  469, 4488, 6086, 3732],
       [4304, 8927, 1861, 4681,  272, 2264, 9845, 2359, 7534, 3297]])

In [32]:
N.max()

9911

In [33]:
N.min()

73

Zad.6. Podano następujący skrypt:
    
```python
np.array(np.nan) / 5
```
Jaki będzie jej wynik? Podaj odpowiedź bez wywoływania.

np.nan

Zad.7. Dodaj do siebie poniższe macierze

```python
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])
```

In [34]:
a = np.array([[1,2,3],
              [4,5,6]])

In [35]:
b = np.array([[10,11,12],
              [13,14,15]])

In [36]:
a + b

array([[11, 13, 15],
       [17, 19, 21]])

Zad.8. Majac ponizsza macierz:

```python
a = np.array([x for x in range(27)])
```
zreshapuj ja do 3 możliwych arrayek 3 wymiarowych. Za kazdym razem nie alokuj wyniku do zmienej.

In [37]:
a = np.array([x for x in range(27)])

In [39]:
a.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Zad.9. Zmień typ danych w arrayce na bool

```python
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])
```

In [41]:
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])

In [42]:
np.array(a, dtype=bool)

array([[ True, False, False],
       [ True,  True,  True],
       [False, False, False]])

Zad.10. Podaj ilość elementów poniższej macierzy, jej kształt i spłaszcz ją.

```python
a2 = np.array([[7,8],
               [9,10],
               [10,11]])
```

In [45]:
a2 = np.array([[7,8],
               [9,10],
               [10,11]])

In [47]:
a2.size

6

In [48]:
a2.shape

(3, 2)

In [49]:
a2.flatten()

array([ 7,  8,  9, 10, 10, 11])

Zad.11. Stworz wektor o 10 elementach z randomowymi wartościami oraz przesortuj go.

In [56]:
N = np.random.randint(1,10000,10)

In [59]:
N.sort()
N

array([1728, 3508, 3719, 4385, 4912, 7482, 7533, 9679, 9681, 9781])

Zad.12. Mając arrayke

Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], 

Sprobuj wyprodukować taka jak poniższa

R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]

In [40]:
Z = np.arange(1,15,dtype=np.uint32)
R = np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


Zad.13. Połącz wertykalnie następujące arrayki

```python
a1 = np.array([[1,2],
               [3,4],
               [5,6]])

a2 = np.array([[7,8],
               [9,10],
               [10,11]])
```

In [61]:
a1 = np.array([[1,2],
               [3,4],
               [5,6]])

In [62]:
a2 = np.array([[7,8],
               [9,10],
               [10,11]])

In [65]:
np.vstack((a1,a2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [10, 11]])

Zad.14. Jaką funkcją można znaleźć najczęściej występującą wartość w arrayce? Przeszukaj dokumentację :)

In [73]:
#sposob 1

In [66]:
a = np.array([1,2,3,1,2,1,1,1,3,2,2,1])
counts = np.bincount(a)
print(np.argmax(counts))

1


In [74]:
#sposob 2

In [72]:
from scipy.stats import mode
mode(a)

ModeResult(mode=array([1]), count=array([6]))

In [75]:
#sposob 3

In [71]:
from statistics import mode
mode(a)

1